name: Clojure CI

on:
  push:
    branches: [ "actions-testing" ]
  pull_request:
    branches: [ "actions-testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        cli: latest           
    - name: Complile Raw EDN
      run: clojure -X:combine
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: commit
      run: |
        # Stage the file, commit and push
        git add edn/raw_data.edn
        git commit -m "CI/CD - Updating raw data"
        git push 
